/* class pour stocker toutes les constantes utilisées par le code
Code écrit par : Hemdene Ben Hammouda*/
public class Constants{

    public static final String BOUTIQUE = 'Conformité Boutique';
    public static final String CREDIT = 'Conformité Crédits';
    public static final String PARENT_BUNDLE = 'Conformité Parent Bundle';
    public static final String DIFFUSION_LBC = 'Conformité Diffusion LBC';
    public static final String DIFFUSION_AVAL = 'Conformité Diffusion AVAL';
    public static final String VISIBILITE_AVAL = 'Conformité Visibilité AVAL';
    public static final String PUB_LOCAL = 'Conformité Pub Local';
    public static final String PUB = 'Conformité Pub';
    public static final String IMMO_NEUF = 'Conformité Immo neuf';
    public static final String CONFORME = 'Conforme';
    public static final String CREATED = 'Created';
    public static final String MODE = 'Fashion';
    public static final String SSII = 'JobServiceCompany';
    public static final String MME = 'Ms';
    public static final String CLOVER = 'CLOVER';
    public static final String MANUEL = 'Manuel';
    public static final String UBIFLOW = 'Ubiflow';
    public static final String ELEMENTS_MANQUANTS = 'Éléments manquants';
    public static final String MISSING_INFO = 'There is some missing informations';
    public static final String YEAH = 'yeah';
}